version: '3'

services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: